{% set version = "1.0.0" %}

package:
  name: flo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flo/flo-{{ version }}.tar.gz
  sha256: 3951ea1101852c98d5d2709fd4d26167827174212838e4764d8e1ff461334a4c

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<3
    - pyyaml
    - jinja2
    - argcomplete
    - networkx

test:
  requires:
    - python {{ python_min }}
  imports:
    - flo
    - flo.commands
    - flo.resources
    - flo.tasks
    - flo.templates

  commands:
    - flo -h

about:
  home: https://github.com/deanmalmgren/flo
  license: MIT
  license_file: LICENSE
  summary: 'Enable rapid iteration and development of data workflows'
  doc_url: https://flo.readthedocs.io/en/latest/
  dev_url: https://github.com/deanmalmgren/flo

extra:
  recipe-maintainers:
    - pmlandwehr
